version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: todolist-api
    ports:
      - "3000:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tododb
    depends_on:
      - mongo

volumes:
  mongo-data:
